--- 
- name: playbook web
  hosts: win
  tasks:
  - name: web1
    win_iis_website:
      name: "web1"
      state: started
      port: 80
      ip: 10.56.1.12
      hostname: 
      physical_path: C:\inetpub\WEB1
      register: website
  - name: web2
    win_iis_website:
        name: "web2"
        state: started
        port: 80
        ip: 10.56.1.22
        hostname: 
        physical_path: C:\WEB2
        register: website
- name: Remove Default Web Site
  win_iis_website:
    name: "Default Web Site"
    state: present
