---
- name: Install IIS
  hosts: win
  gather_facts: false
  tasks:
    - name: Install IIS
      win_feature:
        name: Web-Server,Web-Common-Http,NET-Framework-Core
        state: present
        include_sub_features: yes
        include_management_tools: yes
        